# Federal University of Ceará
# Teleinformatics Departament
# Graduate Program in Teleinformatics Engeneering
## TIP8419 - Tensor Algebra
## Homework 5 - Unfolding, folding, and $n$-mode product
### Report and Simulation results

- Ezequias Márcio - 497779

To run this notebook properly, it is necessary Python3 installed alongside alongside with the packages listed below:

- `numpy 1.17.2`

Make sure that the files `tensoralg.py` and `ta_simulations.py` are in the same directory as this notebook. In this files, it can be found the tensor algebra module functions and the code listings of the simulations.

In [1]:
# Importing the simulation module:
import numpy as np
import tensoralg
np.set_printoptions(3, linewidth=175)

# Loading files:
kolda_tensor = np.load('files/kolda-ex/kolda_tensor.npy')
kolda_m1 = np.load('files/kolda-ex/kolda_tensor_m1.npy')
kolda_m2 = np.load('files/kolda-ex/kolda_tensor_m2.npy')
kolda_m3 = np.load('files/kolda-ex/kolda_tensor_m3.npy')

# unfolding_folding.mat:
tenX = np.load('files/unfolding-folding/tenX.npy')
X1 = np.load('files/unfolding-folding/X1.npy')
X2 = np.load('files/unfolding-folding/X2.npy')
X3 = np.load('files/unfolding-folding/X3.npy')

# multilinear_product.mat:
A = np.load('files/multilinear-product/A.npy')
B = np.load('files/multilinear-product/B.npy')
C = np.load('files/multilinear-product/C.npy')
mtenX = np.load('files/multilinear-product/mtenX.npy')
tenY = np.load('files/multilinear-product/tenY.npy')

### Problem 1 - Unfolding

For a third-order tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ , using the concept of n-mode fibers, implement the function unfold according to the following prototype:

\begin{equation}
 [\mathbf{\mathcal{X}}]_{(n)} = \text{unfold}(\mathbf{\mathcal{X}},n) 
\end{equation}

Hint: Use the file “unfolding_folding.mat” to validate your function.

### Solution: 

The functioning of the implemented routine is shown below. First, using the Kolda's 3rd-order tensor example:

In [2]:
kolda_tensor = np.complex_(kolda_tensor) + 1j*kolda_tensor; print(kolda_tensor, 'Tensor shape: ', kolda_tensor.shape)

[[[ 1. +1.j  4. +4.j  7. +7.j 10.+10.j]
  [ 2. +2.j  5. +5.j  8. +8.j 11.+11.j]
  [ 3. +3.j  6. +6.j  9. +9.j 12.+12.j]]

 [[13.+13.j 16.+16.j 19.+19.j 22.+22.j]
  [14.+14.j 17.+17.j 20.+20.j 23.+23.j]
  [15.+15.j 18.+18.j 21.+21.j 24.+24.j]]] Tensor shape:  (2, 3, 4)


We have for the $1$-mode unfolding the matrix:

In [3]:
print(tensoralg.unfold(kolda_tensor, 1))

[[ 1. +1.j  4. +4.j  7. +7.j 10.+10.j 13.+13.j 16.+16.j 19.+19.j 22.+22.j]
 [ 2. +2.j  5. +5.j  8. +8.j 11.+11.j 14.+14.j 17.+17.j 20.+20.j 23.+23.j]
 [ 3. +3.j  6. +6.j  9. +9.j 12.+12.j 15.+15.j 18.+18.j 21.+21.j 24.+24.j]]


For the $2$-mode unfolding we have the matrix:

In [4]:
print(tensoralg.unfold(kolda_tensor, 2))

[[ 1. +1.j  2. +2.j  3. +3.j 13.+13.j 14.+14.j 15.+15.j]
 [ 4. +4.j  5. +5.j  6. +6.j 16.+16.j 17.+17.j 18.+18.j]
 [ 7. +7.j  8. +8.j  9. +9.j 19.+19.j 20.+20.j 21.+21.j]
 [10.+10.j 11.+11.j 12.+12.j 22.+22.j 23.+23.j 24.+24.j]]


And, for the $3$-mode unfolding:

In [5]:
print(tensoralg.unfold(kolda_tensor, 3))

[[ 1. +1.j  2. +2.j  3. +3.j  4. +4.j  5. +5.j  6. +6.j  7. +7.j  8. +8.j  9. +9.j 10.+10.j 11.+11.j 12.+12.j]
 [13.+13.j 14.+14.j 15.+15.j 16.+16.j 17.+17.j 18.+18.j 19.+19.j 20.+20.j 21.+21.j 22.+22.j 23.+23.j 24.+24.j]]


- Validating the implemented routine using the provided data in the file `unfolding_folding.mat`

For the $1$-mode unfolding:

In [6]:
print(f'Tensor X:\n\n{tenX}')
print(f'''\nImplemented unfold:\n\n{tensoralg.unfold(tenX, 1)}\n
Real Value:\n
{X1}''')

Tensor X:

[[[ -1.816   3.84    2.261   0.987]
  [ -1.178   1.82    5.018   3.602]
  [  3.202  -6.178  -7.122  -4.354]]

 [[ -0.734   1.719   0.026  -0.342]
  [ -0.126   0.521  -1.19   -1.054]
  [  0.985  -2.506   1.02    1.338]]

 [[  1.434  -3.182  -0.994  -0.119]
  [  0.618  -1.246  -1.094  -0.606]
  [ -2.253   4.888   2.149   0.677]]

 [[ -1.182   2.151   3.315   2.179]
  [ -1.493   1.63    9.942   7.551]
  [  2.725  -3.999 -12.722  -9.26 ]]

 [[ -2.226   4.525   3.731   2.01 ]
  [ -1.822   2.462   9.624   7.123]
  [  4.258  -7.561 -12.936  -8.68 ]]]

Implemented unfold:

[[ -1.816   3.84    2.261   0.987  -0.734   1.719   0.026  -0.342   1.434  -3.182  -0.994  -0.119  -1.182   2.151   3.315   2.179  -2.226   4.525   3.731   2.01 ]
 [ -1.178   1.82    5.018   3.602  -0.126   0.521  -1.19   -1.054   0.618  -1.246  -1.094  -0.606  -1.493   1.63    9.942   7.551  -1.822   2.462   9.624   7.123]
 [  3.202  -6.178  -7.122  -4.354   0.985  -2.506   1.02    1.338  -2.253   4.888   2.149  

For the $2$-mode unfolding:

In [7]:
print(f'''{tensoralg.unfold(tenX, 2)}\n
Real Value:\n
{X2}''')

[[ -1.816  -1.178   3.202  -0.734  -0.126   0.985   1.434   0.618  -2.253  -1.182  -1.493   2.725  -2.226  -1.822   4.258]
 [  3.84    1.82   -6.178   1.719   0.521  -2.506  -3.182  -1.246   4.888   2.151   1.63   -3.999   4.525   2.462  -7.561]
 [  2.261   5.018  -7.122   0.026  -1.19    1.02   -0.994  -1.094   2.149   3.315   9.942 -12.722   3.731   9.624 -12.936]
 [  0.987   3.602  -4.354  -0.342  -1.054   1.338  -0.119  -0.606   0.677   2.179   7.551  -9.26    2.01    7.123  -8.68 ]]

Real Value:

[[ -1.816  -1.178   3.202  -0.734  -0.126   0.985   1.434   0.618  -2.253  -1.182  -1.493   2.725  -2.226  -1.822   4.258]
 [  3.84    1.82   -6.178   1.719   0.521  -2.506  -3.182  -1.246   4.888   2.151   1.63   -3.999   4.525   2.462  -7.56 ]
 [  2.262   5.018  -7.122   0.026  -1.19    1.02   -0.994  -1.094   2.149   3.315   9.942 -12.722   3.731   9.624 -12.936]
 [  0.987   3.602  -4.354  -0.342  -1.054   1.338  -0.119  -0.606   0.677   2.179   7.552  -9.26    2.009   7.123  -8.68 ]]


For the $3$-mode unfolding:

In [8]:
print(f'''{tensoralg.unfold(tenX, 3)}\n
Real Value:\n
{X3}''')

[[ -1.816  -1.178   3.202   3.84    1.82   -6.178   2.261   5.018  -7.122   0.987   3.602  -4.354]
 [ -0.734  -0.126   0.985   1.719   0.521  -2.506   0.026  -1.19    1.02   -0.342  -1.054   1.338]
 [  1.434   0.618  -2.253  -3.182  -1.246   4.888  -0.994  -1.094   2.149  -0.119  -0.606   0.677]
 [ -1.182  -1.493   2.725   2.151   1.63   -3.999   3.315   9.942 -12.722   2.179   7.551  -9.26 ]
 [ -2.226  -1.822   4.258   4.525   2.462  -7.561   3.731   9.624 -12.936   2.01    7.123  -8.68 ]]

Real Value:

[[ -1.816  -1.178   3.202   3.84    1.82   -6.178   2.262   5.018  -7.122   0.987   3.602  -4.354]
 [ -0.734  -0.126   0.985   1.719   0.521  -2.506   0.026  -1.19    1.02   -0.342  -1.054   1.338]
 [  1.434   0.618  -2.253  -3.182  -1.246   4.888  -0.994  -1.094   2.149  -0.119  -0.606   0.677]
 [ -1.182  -1.493   2.725   2.151   1.63   -3.999   3.315   9.942 -12.722   2.179   7.552  -9.26 ]
 [ -2.226  -1.822   4.258   4.525   2.462  -7.56    3.731   9.624 -12.936   2.009   7.123  -8.

As can be seen above, the impelemted roitine works well for 3rd-Order tensors, taking each $n$-mode fibers in the standard form (Kolda notation).

### Problem 2 - Folding

Implement the function fold that converts the unfolding $[\mathbf{\mathcal{X}}]_{(n)}$ obtained with $\text{unfold} (\mathbf{\mathcal{X}}, n)$ back to the tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ (i.e., a 3-d array in Matlab/Octave), according to the following prototype:

\begin{equation}
 \mathbf{\mathcal{X}} = fold([\mathbf{\mathcal{X}}]_{(n)},[I,J,K],n) 
\end{equation}

### Solution: 

Again, functioning of the implemented routine is shown below. Using the Kolda's unfoldings example we have:

For $1$-mode matrix:

In [9]:
kolda_m1 = np.complex_(kolda_m1) + 1j*kolda_m1; print(kolda_m1)
print(f'\nFold mode 1:\n{tensoralg.fold(kolda_m1, kolda_tensor.shape, 1)}')

[[ 1. +1.j  4. +4.j  7. +7.j 10.+10.j 13.+13.j 16.+16.j 19.+19.j 22.+22.j]
 [ 2. +2.j  5. +5.j  8. +8.j 11.+11.j 14.+14.j 17.+17.j 20.+20.j 23.+23.j]
 [ 3. +3.j  6. +6.j  9. +9.j 12.+12.j 15.+15.j 18.+18.j 21.+21.j 24.+24.j]]

Fold mode 1:
[[[ 1. +1.j  4. +4.j  7. +7.j 10.+10.j]
  [ 2. +2.j  5. +5.j  8. +8.j 11.+11.j]
  [ 3. +3.j  6. +6.j  9. +9.j 12.+12.j]]

 [[13.+13.j 16.+16.j 19.+19.j 22.+22.j]
  [14.+14.j 17.+17.j 20.+20.j 23.+23.j]
  [15.+15.j 18.+18.j 21.+21.j 24.+24.j]]]


For $2$-mode matrix:

In [10]:
kolda_m2 = np.complex_(kolda_m2) + 1j*kolda_m2; print(kolda_m2)
print(f'\nFold mode 2:\n{tensoralg.fold(kolda_m2, kolda_tensor.shape, 2)}')

[[ 1. +1.j  2. +2.j  3. +3.j 13.+13.j 14.+14.j 15.+15.j]
 [ 4. +4.j  5. +5.j  6. +6.j 16.+16.j 17.+17.j 18.+18.j]
 [ 7. +7.j  8. +8.j  9. +9.j 19.+19.j 20.+20.j 21.+21.j]
 [10.+10.j 11.+11.j 12.+12.j 22.+22.j 23.+23.j 24.+24.j]]

Fold mode 2:
[[[ 1. +1.j  4. +4.j  7. +7.j 10.+10.j]
  [ 2. +2.j  5. +5.j  8. +8.j 11.+11.j]
  [ 3. +3.j  6. +6.j  9. +9.j 12.+12.j]]

 [[13.+13.j 16.+16.j 19.+19.j 22.+22.j]
  [14.+14.j 17.+17.j 20.+20.j 23.+23.j]
  [15.+15.j 18.+18.j 21.+21.j 24.+24.j]]]


For $3$-mode matrix:

In [11]:
kolda_m3 = np.complex_(kolda_m3) + 1j*kolda_m3; print(kolda_m3)
print(f'\nFold mode 3:\n{tensoralg.fold(kolda_m3, kolda_tensor.shape, 3)}')

[[ 1. +1.j  2. +2.j  3. +3.j  4. +4.j  5. +5.j  6. +6.j  7. +7.j  8. +8.j  9. +9.j 10.+10.j 11.+11.j 12.+12.j]
 [13.+13.j 14.+14.j 15.+15.j 16.+16.j 17.+17.j 18.+18.j 19.+19.j 20.+20.j 21.+21.j 22.+22.j 23.+23.j 24.+24.j]]

Fold mode 3:
[[[ 1. +1.j  4. +4.j  7. +7.j 10.+10.j]
  [ 2. +2.j  5. +5.j  8. +8.j 11.+11.j]
  [ 3. +3.j  6. +6.j  9. +9.j 12.+12.j]]

 [[13.+13.j 16.+16.j 19.+19.j 22.+22.j]
  [14.+14.j 17.+17.j 20.+20.j 23.+23.j]
  [15.+15.j 18.+18.j 21.+21.j 24.+24.j]]]


- Validating the implemented routine using the provided data in the file `unfolding_folding.mat`

For the $1$-mode matrix:

In [12]:
print(f'''X1:\n{X1}\n
Folding :\n
{tensoralg.fold(X1, tenX.shape, 1)}''')

X1:
[[ -1.816   3.84    2.262   0.987  -0.734   1.719   0.026  -0.342   1.434  -3.182  -0.994  -0.119  -1.182   2.151   3.315   2.179  -2.226   4.525   3.731   2.009]
 [ -1.178   1.82    5.018   3.602  -0.126   0.521  -1.19   -1.054   0.618  -1.246  -1.094  -0.606  -1.493   1.63    9.942   7.552  -1.822   2.462   9.624   7.123]
 [  3.202  -6.178  -7.122  -4.354   0.985  -2.506   1.02    1.338  -2.253   4.888   2.149   0.677   2.725  -3.999 -12.722  -9.26    4.258  -7.56  -12.936  -8.68 ]]

Folding :

[[[ -1.816   3.84    2.262   0.987]
  [ -1.178   1.82    5.018   3.602]
  [  3.202  -6.178  -7.122  -4.354]]

 [[ -0.734   1.719   0.026  -0.342]
  [ -0.126   0.521  -1.19   -1.054]
  [  0.985  -2.506   1.02    1.338]]

 [[  1.434  -3.182  -0.994  -0.119]
  [  0.618  -1.246  -1.094  -0.606]
  [ -2.253   4.888   2.149   0.677]]

 [[ -1.182   2.151   3.315   2.179]
  [ -1.493   1.63    9.942   7.552]
  [  2.725  -3.999 -12.722  -9.26 ]]

 [[ -2.226   4.525   3.731   2.009]
  [ -1.822   2.462

For the $2$-mode matrix:

In [13]:
print(f'''X2:\n{X2}\n
Folding :\n
{tensoralg.fold(X2, tenX.shape, 2)}''')

X2:
[[ -1.816  -1.178   3.202  -0.734  -0.126   0.985   1.434   0.618  -2.253  -1.182  -1.493   2.725  -2.226  -1.822   4.258]
 [  3.84    1.82   -6.178   1.719   0.521  -2.506  -3.182  -1.246   4.888   2.151   1.63   -3.999   4.525   2.462  -7.56 ]
 [  2.262   5.018  -7.122   0.026  -1.19    1.02   -0.994  -1.094   2.149   3.315   9.942 -12.722   3.731   9.624 -12.936]
 [  0.987   3.602  -4.354  -0.342  -1.054   1.338  -0.119  -0.606   0.677   2.179   7.552  -9.26    2.009   7.123  -8.68 ]]

Folding :

[[[ -1.816   3.84    2.262   0.987]
  [ -1.178   1.82    5.018   3.602]
  [  3.202  -6.178  -7.122  -4.354]]

 [[ -0.734   1.719   0.026  -0.342]
  [ -0.126   0.521  -1.19   -1.054]
  [  0.985  -2.506   1.02    1.338]]

 [[  1.434  -3.182  -0.994  -0.119]
  [  0.618  -1.246  -1.094  -0.606]
  [ -2.253   4.888   2.149   0.677]]

 [[ -1.182   2.151   3.315   2.179]
  [ -1.493   1.63    9.942   7.552]
  [  2.725  -3.999 -12.722  -9.26 ]]

 [[ -2.226   4.525   3.731   2.009]
  [ -1.822   2.

For the $3$-mode matrix:

In [14]:
print(f'''X3:\n{X3}\n
Folding :\n
{tensoralg.fold(X3, tenX.shape, 3)}''')

X3:
[[ -1.816  -1.178   3.202   3.84    1.82   -6.178   2.262   5.018  -7.122   0.987   3.602  -4.354]
 [ -0.734  -0.126   0.985   1.719   0.521  -2.506   0.026  -1.19    1.02   -0.342  -1.054   1.338]
 [  1.434   0.618  -2.253  -3.182  -1.246   4.888  -0.994  -1.094   2.149  -0.119  -0.606   0.677]
 [ -1.182  -1.493   2.725   2.151   1.63   -3.999   3.315   9.942 -12.722   2.179   7.552  -9.26 ]
 [ -2.226  -1.822   4.258   4.525   2.462  -7.56    3.731   9.624 -12.936   2.009   7.123  -8.68 ]]

Folding :

[[[ -1.816   3.84    2.262   0.987]
  [ -1.178   1.82    5.018   3.602]
  [  3.202  -6.178  -7.122  -4.354]]

 [[ -0.734   1.719   0.026  -0.342]
  [ -0.126   0.521  -1.19   -1.054]
  [  0.985  -2.506   1.02    1.338]]

 [[  1.434  -3.182  -0.994  -0.119]
  [  0.618  -1.246  -1.094  -0.606]
  [ -2.253   4.888   2.149   0.677]]

 [[ -1.182   2.151   3.315   2.179]
  [ -1.493   1.63    9.942   7.552]
  [  2.725  -3.999 -12.722  -9.26 ]]

 [[ -2.226   4.525   3.731   2.009]
  [ -1.822  

### Problem 3 - Tensor x Matrix Product

For given matrices $A \in \mathbb{C}^{P \times I}$, $B \in \mathbb{C}^{Q \times J}$ and $C \in \mathbb{C}^{R \times K}$ and tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ , calculate the tensor $\mathbf{\mathcal{Y}} \in \mathbb{C}^{P \times Q \times R}$ via the following multilinear transformation:

\begin{equation}
    \mathbf{\mathcal{Y}} = \mathbf{\mathcal{X}} \times_{1} \mathbf{A} \times_{2} \mathbf{B} \times_{3} \mathbf{C}
\end{equation}

### Solution

To show the functioning of the implemented function, we have the example below for the $1$-mode pdoduct between the matrix U and the Kolda's tensor:

In [15]:
U = np.array([[1, 3, 5],[2, 4, 6]]); U = np.complex_(U) + 1j*U; print(f'Matrix U:\n\n{U}')

Matrix U:

[[1.+1.j 3.+3.j 5.+5.j]
 [2.+2.j 4.+4.j 6.+6.j]]


In [16]:
print(f'1-mode product:\n\n{tensoralg.m_mode_prod(kolda_tensor, [U])}\n')

1-mode product:

[[[0. +44.j 0. +98.j 0.+152.j 0.+206.j]
  [0. +56.j 0.+128.j 0.+200.j 0.+272.j]]

 [[0.+260.j 0.+314.j 0.+368.j 0.+422.j]
  [0.+344.j 0.+416.j 0.+488.j 0.+560.j]]]



- Validating the implemented routine using the provided data in the file `multilinear_product.mat`

In [17]:
print(f'''Multilinear Product:\n\n{tensoralg.m_mode_prod(mtenX, [A, B, C])}''')

Multilinear Product:

[[[-2.130e+00 -1.259e+00  3.167e-01 -9.018e+00  2.583e-01]
  [ 1.341e+00  1.559e+00  8.322e-01  6.595e+00 -8.034e-03]
  [ 2.914e+00  1.560e-01  1.960e+00  9.945e+00  7.400e-01]
  [ 5.543e-01  3.017e+00 -1.378e+00  6.128e+00 -1.064e+00]]

 [[ 6.851e+00 -1.151e+01 -1.193e+01 -7.727e+00 -1.960e+00]
  [ 1.729e+00 -1.990e+00  7.860e+00  6.724e+00  3.288e+00]
  [-1.699e+00  3.308e+00  1.214e+01  8.481e+00  3.731e+00]
  [-2.438e+00  4.773e+00  8.103e+00  6.665e+00  1.988e+00]]

 [[ 3.761e+00 -4.289e+00 -5.123e+00  5.529e-01 -9.285e-01]
  [ 1.601e-01 -1.487e+00  2.939e+00  4.445e-02  1.379e+00]
  [-1.934e+00  1.319e+00  4.258e+00 -6.264e-01  1.251e+00]
  [-1.253e+00  7.308e-01  3.969e+00  2.161e-01  1.278e+00]]]


In [18]:
print(f'''Real result:\n\n{tenY}''')

Real result:

[[[-2.130e+00 -1.259e+00  3.166e-01 -9.018e+00  2.583e-01]
  [ 1.341e+00  1.559e+00  8.322e-01  6.595e+00 -8.040e-03]
  [ 2.914e+00  1.560e-01  1.960e+00  9.945e+00  7.400e-01]
  [ 5.543e-01  3.017e+00 -1.378e+00  6.128e+00 -1.064e+00]]

 [[ 6.851e+00 -1.151e+01 -1.193e+01 -7.727e+00 -1.960e+00]
  [ 1.729e+00 -1.990e+00  7.860e+00  6.724e+00  3.288e+00]
  [-1.699e+00  3.308e+00  1.214e+01  8.481e+00  3.731e+00]
  [-2.438e+00  4.773e+00  8.103e+00  6.665e+00  1.988e+00]]

 [[ 3.761e+00 -4.289e+00 -5.123e+00  5.529e-01 -9.285e-01]
  [ 1.601e-01 -1.487e+00  2.939e+00  4.445e-02  1.379e+00]
  [-1.934e+00  1.319e+00  4.258e+00 -6.264e-01  1.251e+00]
  [-1.253e+00  7.308e-01  3.969e+00  2.161e-01  1.278e+00]]]
