# Federal University of Ceará
# Teleinformatics Departament
# Graduate Program in Teleinformatics Engeneering
## TIP8419 - Tensor Algebra
## Homework 6 - High Order Singular Value Decomposition (HOSVD) and Higher-Order Orthogonal Iteration (HOOI) Algorithm
### Report and Simulation results

- Ezequias Márcio - 497779

To run this notebook properly, it is necessary Python3 installed alongside with the packages listed below:

- `numpy 1.17.2`
- `scipy 1.4.1`
- `tdqm 4.36.1`
- `bokeh 1.3.4`

Make sure that the files `tensoralg.py` and `ta_simulations.py` are in the same directory as this notebook. In this files, it can be found the tensor algebra module functions and the code listings of the simulations.

In [1]:
# Importing the simulation module:
from ta_simulations import *
np.set_printoptions(4, linewidth=175)
# Loading files:
data1 = loadmat('files/hosvd_test.mat'); data2 = loadmat('files/hosvd_denoising.mat')

### Problem 1

For a third-order tensor $\mathbf{\mathcal{X}} \in \mathbb{C}^{I \times J \times K}$ implement the truncated high-order singular value decomposition (HOSVD), using the following prototype function:

\begin{equation}
    [\mathbf{\mathcal{S}},\mathbf{U}^{(1)},\mathbf{U}^{(2)},\mathbf{U}^{(3)}] = \text{hosvd}(\mathbf{\mathcal{X}})
\end{equation}

### Solution: 

The functioning of the implemented routine is shown in the cell below where the third-order tensor  $\mathbf{\mathcal{X}}$  is randomly generated, and then it is applied the decomposition and calculated the Normalized Mean Square Error between the tensor and their reconstructed version for comparison.

In [2]:
# Generate data and applying the decomposition:
I, J, K = 2, 4, 3
tensor = np.random.rand(K, I, J*2).view(np.complex_); core, matrices_u = tensoralg.hosvd(tensor)
tensor_hat = tensoralg.m_mode_prod(core, matrices_u) # Reconstructing tensor
nmse_tensor = norm_mse(tensor, tensor_hat) # Normalized Mean Square Error
print(f'''Tensor {tensor.shape}:\n{tensor}\n\nReconstructed Tensor {tensor.shape}:\n{tensor}\n\nNMSE Result: {nmse_tensor}''')

Tensor (3, 2, 4):
[[[0.179 +0.7066j 0.6017+0.5289j 0.8895+0.6512j 0.5224+0.4758j]
  [0.13  +0.8764j 0.7053+0.8471j 0.3777+0.5329j 0.6613+0.3432j]]

 [[0.7646+0.9806j 0.0269+0.6327j 0.1301+0.3044j 0.9962+0.568j ]
  [0.8037+0.0694j 0.1189+0.0305j 0.8929+0.9995j 0.8164+0.5073j]]

 [[0.8056+0.9j    0.3744+0.6389j 0.4471+0.5578j 0.5534+0.4731j]
  [0.4352+0.4452j 0.6607+0.3656j 0.8446+0.3734j 0.1227+0.0654j]]]

Reconstructed Tensor (3, 2, 4):
[[[0.179 +0.7066j 0.6017+0.5289j 0.8895+0.6512j 0.5224+0.4758j]
  [0.13  +0.8764j 0.7053+0.8471j 0.3777+0.5329j 0.6613+0.3432j]]

 [[0.7646+0.9806j 0.0269+0.6327j 0.1301+0.3044j 0.9962+0.568j ]
  [0.8037+0.0694j 0.1189+0.0305j 0.8929+0.9995j 0.8164+0.5073j]]

 [[0.8056+0.9j    0.3744+0.6389j 0.4471+0.5578j 0.5534+0.4731j]
  [0.4352+0.4452j 0.6607+0.3656j 0.8446+0.3734j 0.1227+0.0654j]]]

NMSE Result: 3.2312806742269546e-31


As can be seen by the result above, the small error indicates that the implemente HOSVD algorithm has a good performance for the multilinear rank approximation. Also, in the cell below is verified if the core tensor obtained with thos routine attends the properties of all-orthogonality and the order of the n-mode singular values.

In [3]:
all_orth(core) # All orthogonality and ...
nth_singular_val(core) # n-th singular values ordering

Dimension I=2: [0. 0.]
Dimension J=4: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimension K=3: [0. 0. 0. 0. 0. 0.]

N-th singular values (I, J, K):
[3.9674 1.3286]
[3.8328 1.2218 1.0643 0.4353]
[3.855  1.4534 0.7293]


### Validation

Using the file “hosvd_test.mat” to validate the implemented routine in the cell below.

In [4]:
# Test data:
X_test = data1['tenX'].transpose(2, 0, 1); S_test = data1['tenS'].transpose(2, 0, 1)
U1_test = data1['U1']; U2_test = data1['U2']; U3_test = data1['U3']
# Applying the decomposition and Reconstructing tensor X:
S_hat, U_hat_list = tensoralg.hosvd(X_test); X_hat = tensoralg.m_mode_prod(S_hat, U_hat_list)
# Normalized Mean Square Errors:
nmse_x = norm_mse(X_test, X_hat); nmse_s = norm_mse(S_test, S_hat)
nmse_u1 = norm_mse(U1_test, U_hat_list[0]); nmse_u2 =norm_mse(U2_test, U_hat_list[1]); nmse_u3 = norm_mse(U3_test, U_hat_list[2])
print(f'''Data for Problem 1 validation: Tensor X {X_test.shape}\n''')
print(f'''Normalized Mean Square Errors:\n\nTensor X_hat: {nmse_x}\n\nCore tensor S: {nmse_s}\n\nU1: {nmse_u1}\nU2: {nmse_u2}\nU3: {nmse_u3}''')

Data for Problem 1 validation: Tensor X (5, 3, 4)

Normalized Mean Square Errors:

Tensor X_hat: 3.5036209766369374e-31

Core tensor S: 1.5607066827251088

U1: 0.0
U2: 0.0005771204134077603
U3: 0.04761713475835911


As can be seen by the result above, the implemented algorithm is working as expected, presenting a small error for the reconstructed tensor, and the difference betwen the core tensor provided and the matrices $\mathbf{U}_n$ is due to the lack of uniqueness for the core tensor and these matrices obtained by the HOSVD algorithm.

### HOOI Algorithm:

The results of Problem 1 obtained using the implemented HOOI algorithm for the decomposition is shown in the cell below.

In [5]:
core, matrices_u = tensoralg.hooi(tensor, verb=True); tensor_hat = tensoralg.m_mode_prod(core, matrices_u) # HOOI and Reconstruction
nmse_tensor = norm_mse(tensor, tensor_hat) # Normalized Mean Square Error
print(f'''Tensor {tensor.shape}:\n{tensor}\n\nReconstructed Tensor {tensor.shape}:\n{tensor}\n\nNMSE Result HOOI: {nmse_tensor}\n
All-orthogonality and n-th mode singular values:''')
all_orth(core) # All orthogonality and ...
nth_singular_val(core) # n-th singular values ordering

Number of iterations: 1; Error: 4.664258731808323e-16
Tensor (3, 2, 4):
[[[0.179 +0.7066j 0.6017+0.5289j 0.8895+0.6512j 0.5224+0.4758j]
  [0.13  +0.8764j 0.7053+0.8471j 0.3777+0.5329j 0.6613+0.3432j]]

 [[0.7646+0.9806j 0.0269+0.6327j 0.1301+0.3044j 0.9962+0.568j ]
  [0.8037+0.0694j 0.1189+0.0305j 0.8929+0.9995j 0.8164+0.5073j]]

 [[0.8056+0.9j    0.3744+0.6389j 0.4471+0.5578j 0.5534+0.4731j]
  [0.4352+0.4452j 0.6607+0.3656j 0.8446+0.3734j 0.1227+0.0654j]]]

Reconstructed Tensor (3, 2, 4):
[[[0.179 +0.7066j 0.6017+0.5289j 0.8895+0.6512j 0.5224+0.4758j]
  [0.13  +0.8764j 0.7053+0.8471j 0.3777+0.5329j 0.6613+0.3432j]]

 [[0.7646+0.9806j 0.0269+0.6327j 0.1301+0.3044j 0.9962+0.568j ]
  [0.8037+0.0694j 0.1189+0.0305j 0.8929+0.9995j 0.8164+0.5073j]]

 [[0.8056+0.9j    0.3744+0.6389j 0.4471+0.5578j 0.5534+0.4731j]
  [0.4352+0.4452j 0.6607+0.3656j 0.8446+0.3734j 0.1227+0.0654j]]]

NMSE Result HOOI: 2.175530951725019e-31

All-orthogonality and n-th mode singular values:
Dimension I=2: [0. 0.]
D

As can be seen by the result above, the implemented HOOI algorithm gives a better aproximation in the squared norm sense as expected, conveging fast (1 iteration was required) due to the HOSVD initialization.

### Problem 2

Consider the two third-order tensors  $\mathbf{\mathcal{X}} \in \mathbb{C}^{8 \times 4 \times 10}$ and $\mathbf{\mathcal{X}} \in \mathbb{C}^{5 \times 5 \times 5}$ provided in the data file “hosvd_denoising.mat”. By using your HOSVD prototype function, find a low multilinear rank approximation for these tensors, defined as $\mathbf{\mathcal{\tilde{X}}} \in \mathbb{C}^{R_{1} \times R_{2} \times R_{3}}$  and $\mathbf{\mathcal{\tilde{Y}}} \in \mathbb{C}^{P_{1} \times P_{2} \times P_{3}}$. Then, calculate the normalized mean square error (NMSE) between the original tensor and its approximation, i.e.:

\begin{equation}
    \text{NMSE}(\mathbf{\mathcal{\tilde{X}}}) = \frac{||\mathbf{\mathcal{\tilde{X}}} - \mathbf{\mathcal{X}}||^{2}_{F}}{||\mathbf{\mathcal{X}}||^{2}_{F}}
\end{equation}

\begin{equation}
    \text{NMSE}(\mathbf{\mathcal{\tilde{Y}}}) = \frac{||\mathbf{\mathcal{\tilde{Y}}} - \mathbf{\mathcal{Y}}||^{2}_{F}}{||\mathbf{\mathcal{Y}}||^{2}_{F}}
\end{equation}

### Solution:

First the profile of the 1-mode, 2-mode and 3-mode singular values of these tensors is shown in the cell below. They are obtained via HOSVD, and the shapes are in the Numpy's notation $(K, I, J)$.

In [6]:
# Loading data:
tensor_x = data2['tenX_noise'].transpose(2, 0, 1); tensor_y = data2['tenY_noise'].transpose(2, 0, 1)
core_x, _ = tensoralg.hosvd(tensor_x); core_y, _ = tensoralg.hosvd(tensor_y); 
print(f'Tensor X {tensor_x.shape}:')
nth_singular_val(core_x)
print(f'\nTensor Y {tensor_y.shape}:')
nth_singular_val(core_y)

Tensor X (10, 8, 4):

N-th singular values (I, J, K):
[8.1751e+01 3.0525e+01 9.2473e-02 7.1115e-02 6.0448e-02 5.6937e-02 5.0975e-02 4.9795e-02]
[77.1635 36.2239 18.6487  0.951 ]
[7.6196e+01 3.2575e+01 2.0674e+01 1.4816e+01 1.0058e+01 6.3973e-02 5.9474e-02 5.7325e-02 3.8697e-02 3.5704e-02]

Tensor Y (5, 5, 5):

N-th singular values (I, J, K):
[6.9484 0.5317 0.4889 0.4173 0.3624]
[6.9479 0.5884 0.4831 0.4045 0.3021]
[6.9415 0.5561 0.5144 0.4414 0.3933]


As can be seen above, the two tensors are full rank, so to ilustrate the low multilinear rank approximation it will be chosen $R_{1}, R_{2}, R_{3} = 
6, 3, 7$ and $P_{1}, P_{2}, P_{3} = 4, 4, 3$. The NMSE results are shown in the cell below.

In [7]:
# Tuncated HOSVD:
target_x, Ux = tensoralg.hosvd(tensor_x, [6, 3, 7]); target_y, Uy = tensoralg.hosvd(tensor_y, [4, 4, 3])
# Reconstruction:
rec_tensor_x = tensoralg.m_mode_prod(target_x, Ux); rec_tensor_y = tensoralg.m_mode_prod(target_y, Uy)
nmse_x = norm_mse(tensor_x, rec_tensor_x); nmse_y = norm_mse(tensor_y, rec_tensor_y)
print(f'''NMSE X: {nmse_x} \nNMSE Y: {nmse_y}''')

NMSE X: 0.00011976217163409791 
NMSE Y: 0.00991106315233519


In [8]:
# Tuncated HOOi with HOSVD initialization:
target_x, Ux = tensoralg.hooi(tensor_x, rank_list=[6, 3, 7]); target_y, Uy = tensoralg.hosvd(tensor_y, rank_list=[4, 4, 3])
# Reconstruction:
rec_tensor_x = tensoralg.m_mode_prod(target_x, Ux); rec_tensor_y = tensoralg.m_mode_prod(target_y, Uy)
nmse_x = norm_mse(tensor_x, rec_tensor_x); nmse_y = norm_mse(tensor_y, rec_tensor_y)
print(f'''NMSE X: {nmse_x} \nNMSE Y: {nmse_y}''')

NMSE X: 0.00011955278395507484 
NMSE Y: 0.00991106315233519


As can be seen, the HOSVD and the HOOI multilinear rank approximation of these two tensors gives a good aproximation presenting an error $\approx 1\%$ for the considered dimensions.